/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EmpresaRouteRouteImport } from './routes/_empresa/route'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DenuncieRouteImport } from './routes/denuncie'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EmpresaPainelRouteImport } from './routes/_empresa/painel'
import { Route as CategoriaCategoriaRouteImport } from './routes/categoria.$categoria'
import { Route as NoticiaSlugRouteImport } from './routes/noticia.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAssinantesRouteImport } from './routes/_authenticated/admin.assinantes'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminDenunciasRouteImport } from './routes/_authenticated/admin.denuncias'
import { Route as AuthenticatedAdminNoticiasRouteImport } from './routes/_authenticated/admin.noticias'
import { Route as AuthenticatedAdminVagasRouteImport } from './routes/_authenticated/admin.vagas'
import { Route as IrVagaIdRouteImport } from './routes/ir.vaga.$id'
import { Route as AuthenticatedAdminNoticiasIndexRouteImport } from './routes/_authenticated/admin.noticias.index'
import { Route as AuthenticatedAdminNoticiasNovaRouteImport } from './routes/_authenticated/admin.noticias.nova'
import { Route as AuthenticatedAdminNoticiasIdEditarRouteImport } from './routes/_authenticated/admin.noticias.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRouteRoute = EmpresaRouteRouteImport.update({
  id: '/_empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DenuncieRoute = DenuncieRouteImport.update({
  id: '/denuncie',
  path: '/denuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EmpresaPainelRoute = EmpresaPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => EmpresaRouteRoute,
} as any)
const CategoriaCategoriaRoute = CategoriaCategoriaRouteImport.update({
  id: '/categoria/$categoria',
  path: '/categoria/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiaSlugRoute = NoticiaSlugRouteImport.update({
  id: '/noticia/$slug',
  path: '/noticia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAssinantesRoute =
  AuthenticatedAdminAssinantesRouteImport.update({
    id: '/assinantes',
    path: '/assinantes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDenunciasRoute =
  AuthenticatedAdminDenunciasRouteImport.update({
    id: '/denuncias',
    path: '/denuncias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNoticiasRoute =
  AuthenticatedAdminNoticiasRouteImport.update({
    id: '/noticias',
    path: '/noticias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVagasRoute = AuthenticatedAdminVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const IrVagaIdRoute = IrVagaIdRouteImport.update({
  id: '/ir/vaga/$id',
  path: '/ir/vaga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminNoticiasIndexRoute =
  AuthenticatedAdminNoticiasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminNoticiasRoute,
  } as any)
const AuthenticatedAdminNoticiasNovaRoute =
  AuthenticatedAdminNoticiasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedAdminNoticiasRoute,
  } as any)
const AuthenticatedAdminNoticiasIdEditarRoute =
  AuthenticatedAdminNoticiasIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedAdminNoticiasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/denuncie': typeof DenuncieRoute
  '/vagas': typeof VagasRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/painel': typeof EmpresaPainelRoute
  '/categoria/$categoria': typeof CategoriaCategoriaRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/admin/assinantes': typeof AuthenticatedAdminAssinantesRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/denuncias': typeof AuthenticatedAdminDenunciasRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRouteWithChildren
  '/admin/vagas': typeof AuthenticatedAdminVagasRoute
  '/ir/vaga/$id': typeof IrVagaIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/noticias/nova': typeof AuthenticatedAdminNoticiasNovaRoute
  '/admin/noticias/': typeof AuthenticatedAdminNoticiasIndexRoute
  '/admin/noticias/$id/editar': typeof AuthenticatedAdminNoticiasIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/denuncie': typeof DenuncieRoute
  '/vagas': typeof VagasRoute
  '/painel': typeof EmpresaPainelRoute
  '/categoria/$categoria': typeof CategoriaCategoriaRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/admin/assinantes': typeof AuthenticatedAdminAssinantesRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/denuncias': typeof AuthenticatedAdminDenunciasRoute
  '/admin/vagas': typeof AuthenticatedAdminVagasRoute
  '/ir/vaga/$id': typeof IrVagaIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/noticias/nova': typeof AuthenticatedAdminNoticiasNovaRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasIndexRoute
  '/admin/noticias/$id/editar': typeof AuthenticatedAdminNoticiasIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_empresa': typeof EmpresaRouteRouteWithChildren
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/denuncie': typeof DenuncieRoute
  '/vagas': typeof VagasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_empresa/painel': typeof EmpresaPainelRoute
  '/categoria/$categoria': typeof CategoriaCategoriaRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/_authenticated/admin/assinantes': typeof AuthenticatedAdminAssinantesRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/denuncias': typeof AuthenticatedAdminDenunciasRoute
  '/_authenticated/admin/noticias': typeof AuthenticatedAdminNoticiasRouteWithChildren
  '/_authenticated/admin/vagas': typeof AuthenticatedAdminVagasRoute
  '/ir/vaga/$id': typeof IrVagaIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/noticias/nova': typeof AuthenticatedAdminNoticiasNovaRoute
  '/_authenticated/admin/noticias/': typeof AuthenticatedAdminNoticiasIndexRoute
  '/_authenticated/admin/noticias/$id/editar': typeof AuthenticatedAdminNoticiasIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncie'
    | '/auth'
    | '/denuncie'
    | '/vagas'
    | '/admin'
    | '/painel'
    | '/categoria/$categoria'
    | '/noticia/$slug'
    | '/admin/assinantes'
    | '/admin/banners'
    | '/admin/denuncias'
    | '/admin/noticias'
    | '/admin/vagas'
    | '/ir/vaga/$id'
    | '/admin/'
    | '/admin/noticias/nova'
    | '/admin/noticias/'
    | '/admin/noticias/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/auth'
    | '/denuncie'
    | '/vagas'
    | '/painel'
    | '/categoria/$categoria'
    | '/noticia/$slug'
    | '/admin/assinantes'
    | '/admin/banners'
    | '/admin/denuncias'
    | '/admin/vagas'
    | '/ir/vaga/$id'
    | '/admin'
    | '/admin/noticias/nova'
    | '/admin/noticias'
    | '/admin/noticias/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_empresa'
    | '/anuncie'
    | '/auth'
    | '/denuncie'
    | '/vagas'
    | '/_authenticated/admin'
    | '/_empresa/painel'
    | '/categoria/$categoria'
    | '/noticia/$slug'
    | '/_authenticated/admin/assinantes'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/denuncias'
    | '/_authenticated/admin/noticias'
    | '/_authenticated/admin/vagas'
    | '/ir/vaga/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/noticias/nova'
    | '/_authenticated/admin/noticias/'
    | '/_authenticated/admin/noticias/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EmpresaRouteRoute: typeof EmpresaRouteRouteWithChildren
  AnuncieRoute: typeof AnuncieRoute
  AuthRoute: typeof AuthRoute
  DenuncieRoute: typeof DenuncieRoute
  VagasRoute: typeof VagasRoute
  CategoriaCategoriaRoute: typeof CategoriaCategoriaRoute
  NoticiaSlugRoute: typeof NoticiaSlugRoute
  IrVagaIdRoute: typeof IrVagaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_empresa': {
      id: '/_empresa'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EmpresaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncie': {
      id: '/denuncie'
      path: '/denuncie'
      fullPath: '/denuncie'
      preLoaderRoute: typeof DenuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_empresa/painel': {
      id: '/_empresa/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof EmpresaPainelRouteImport
      parentRoute: typeof EmpresaRouteRoute
    }
    '/categoria/$categoria': {
      id: '/categoria/$categoria'
      path: '/categoria/$categoria'
      fullPath: '/categoria/$categoria'
      preLoaderRoute: typeof CategoriaCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticia/$slug': {
      id: '/noticia/$slug'
      path: '/noticia/$slug'
      fullPath: '/noticia/$slug'
      preLoaderRoute: typeof NoticiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assinantes': {
      id: '/_authenticated/admin/assinantes'
      path: '/assinantes'
      fullPath: '/admin/assinantes'
      preLoaderRoute: typeof AuthenticatedAdminAssinantesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/denuncias': {
      id: '/_authenticated/admin/denuncias'
      path: '/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AuthenticatedAdminDenunciasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/noticias': {
      id: '/_authenticated/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vagas': {
      id: '/_authenticated/admin/vagas'
      path: '/vagas'
      fullPath: '/admin/vagas'
      preLoaderRoute: typeof AuthenticatedAdminVagasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/ir/vaga/$id': {
      id: '/ir/vaga/$id'
      path: '/ir/vaga/$id'
      fullPath: '/ir/vaga/$id'
      preLoaderRoute: typeof IrVagaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/noticias/': {
      id: '/_authenticated/admin/noticias/'
      path: '/'
      fullPath: '/admin/noticias/'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminNoticiasRoute
    }
    '/_authenticated/admin/noticias/nova': {
      id: '/_authenticated/admin/noticias/nova'
      path: '/nova'
      fullPath: '/admin/noticias/nova'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasNovaRouteImport
      parentRoute: typeof AuthenticatedAdminNoticiasRoute
    }
    '/_authenticated/admin/noticias/$id/editar': {
      id: '/_authenticated/admin/noticias/$id/editar'
      path: '/$id/editar'
      fullPath: '/admin/noticias/$id/editar'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasIdEditarRouteImport
      parentRoute: typeof AuthenticatedAdminNoticiasRoute
    }
  }
}

interface AuthenticatedAdminNoticiasRouteChildren {
  AuthenticatedAdminNoticiasNovaRoute: typeof AuthenticatedAdminNoticiasNovaRoute
  AuthenticatedAdminNoticiasIndexRoute: typeof AuthenticatedAdminNoticiasIndexRoute
  AuthenticatedAdminNoticiasIdEditarRoute: typeof AuthenticatedAdminNoticiasIdEditarRoute
}

const AuthenticatedAdminNoticiasRouteChildren: AuthenticatedAdminNoticiasRouteChildren =
  {
    AuthenticatedAdminNoticiasNovaRoute: AuthenticatedAdminNoticiasNovaRoute,
    AuthenticatedAdminNoticiasIndexRoute: AuthenticatedAdminNoticiasIndexRoute,
    AuthenticatedAdminNoticiasIdEditarRoute:
      AuthenticatedAdminNoticiasIdEditarRoute,
  }

const AuthenticatedAdminNoticiasRouteWithChildren =
  AuthenticatedAdminNoticiasRoute._addFileChildren(
    AuthenticatedAdminNoticiasRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssinantesRoute: typeof AuthenticatedAdminAssinantesRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminDenunciasRoute: typeof AuthenticatedAdminDenunciasRoute
  AuthenticatedAdminNoticiasRoute: typeof AuthenticatedAdminNoticiasRouteWithChildren
  AuthenticatedAdminVagasRoute: typeof AuthenticatedAdminVagasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssinantesRoute: AuthenticatedAdminAssinantesRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminDenunciasRoute: AuthenticatedAdminDenunciasRoute,
  AuthenticatedAdminNoticiasRoute: AuthenticatedAdminNoticiasRouteWithChildren,
  AuthenticatedAdminVagasRoute: AuthenticatedAdminVagasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EmpresaRouteRouteChildren {
  EmpresaPainelRoute: typeof EmpresaPainelRoute
}

const EmpresaRouteRouteChildren: EmpresaRouteRouteChildren = {
  EmpresaPainelRoute: EmpresaPainelRoute,
}

const EmpresaRouteRouteWithChildren = EmpresaRouteRoute._addFileChildren(
  EmpresaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EmpresaRouteRoute: EmpresaRouteRouteWithChildren,
  AnuncieRoute: AnuncieRoute,
  AuthRoute: AuthRoute,
  DenuncieRoute: DenuncieRoute,
  VagasRoute: VagasRoute,
  CategoriaCategoriaRoute: CategoriaCategoriaRoute,
  NoticiaSlugRoute: NoticiaSlugRoute,
  IrVagaIdRoute: IrVagaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
